name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # - name: Run Tests (Optional)
      #   run: pytest  # Uncomment if you have tests

      - name: Get Git and Timestamp Info
        id: vars
        run: |
          BRANCH_NAME=$(echo "${{ github.ref_name }}" | tr '[:upper:]' '[:lower:]' | tr '/' '-')
          SHORT_SHA=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date +%s)
          TAG="${BRANCH_NAME}-${SHORT_SHA}-${TIMESTAMP}"
          LATEST_TAG="${BRANCH_NAME}-latest"
          echo "IMAGE_TAG=${TAG}" >> $GITHUB_ENV
          echo "BRANCH_LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV
          echo "Generated Tag: ${TAG}"

      - name: Set up QEMU for Multi-Arch Build
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image to HUB
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.BRANCH_LATEST_TAG }}
            ${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=registry,ref=${{ secrets.DOCKER_IMAGE_NAME }}:latest
          cache-to: type=inline
      
      - name: Send Notification to Microsoft Teams
        if: success()
        run: |
          REPO_URL="docker.io/${{ secrets.DOCKER_IMAGE_NAME }}"
          MESSAGE="## 🚀 Docker Image Successfully Built and Pushed \n
          - **Repository:** ${REPO_URL} \n
          - **Tags:** **${{ env.IMAGE_TAG }}**, **${{ env.BRANCH_LATEST_TAG }}** \n
          - **Branch:** ${{ github.ref_name }} \n
          - **Commit:** ${{ github.sha }} \n
          - **GitHub Actions Run:** (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          
          PAYLOAD="{\"text\": \"${MESSAGE}\" }"
          
          curl -H "Content-Type: application/json" \
               -d "${PAYLOAD}" \
               ${{ secrets.TEAMS_WEBHOOK_URL }}